// Map layer names to a descriptive string to show in the infobox
const friendlyNames: { [key: string]: string } = {
  power_transformer: "Transformer",
  power_tower: "Power tower",
  power_pole: "Power pole",
  power_generator: "Generator",
  power_wind_turbine: "Wind turbine",
  power_substation: "Substation",
  power_substation_point: "Substation",
  power_switch: "Switch",
  power_compensator: "Compensator",
  power_cable: "Cable",
  power_line_1: "Power line",
  power_line_2: "Power line",
  power_line_3: "Power line",
  power_line_4: "Power line",
  power_line_underground_1: "Underground power line",
  power_line_underground_2: "Underground power line",
  power_line_underground_3: "Underground power line",
  power_line_underground_4: "Underground power line",
  power_line_case: "Underground power line",
  power_line_label: "Power line",
  power_solar_panel: "Solar panel",
  power_plant: "Power plant",
  telecoms_communication_line: "Telecoms line",
  telecoms_mast: "Telecoms mast",
  telecoms_data_center: "Telecoms building",
  petroleum_pipeline: "Pipeline",
  petroleum_pipeline_case: "Pipeline",
  petroleum_pipeline_label: "Pipeline",
  petroleum_well: "Well",
  water_pipeline: "Water pipeline",
};

export default friendlyNames;
