FROM node:14 AS build
WORKDIR /app
COPY . .
RUN npm install -g npm@latest
RUN npm install
RUN npm run build

FROM nginx:mainline-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx-site.conf /etc/nginx/conf.d/default.conf
